### PR TITLE
Creation of associations

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/50)

### CODE REVIEW

**Comment by roverwolf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 195 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/50#-Ki6S0guRbHN_D7Pmpw8:-Ki6S0guRbHN_D7Pmpw9:brajgq0) ([raw file](https://github.com/opensalt/opensalt/blob/74c79aeab63ca244c1aa616cfa8f5cf8eb7fe449/src/GithubFilesBundle/Service/GithubImport.php#L195)):*
>  if (is_string($elementAssociated)) {
>             $association->setDestinationNodeIdentifier($elementAssociated);

We should be setting the DestinationNodeUri here as well (are we checking that $elementAssociated is a valid identifier -- UUID before this?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/50)*

**Comment by roverwolf** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/50)*

**Comment by lmsilvera** [comment]
I'm not validating this because that value could be a human coding scheme.

**Comment by roverwolf** [comment]
The identifier shouldn't be either of those since it is supposed to be a UUID per the spec.  We should look at how to encode those types of things in the URI instead.

That wasn't part of this PR though, so I'll merge it in now, but figured I should make sure that comment was somewhere so that we would look into it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/50#-:-Ki6XccTGJ2vdOXlrEKf:b4eyylq)*

**Comment by lmsilvera** [comment]
right, this will be pending to talk in slack.

**Pull request merged**
