### PR TITLE
Add email to user, fix new organization blank error

### PR DESCRIPTION
**Pull request by JorgeLu1s**
fix issues #371 and #382

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/383)

### CODE REVIEW

**Comment by roverwolf** [comment]
#382 states that the username should be an email address, but this PR is adding an additional field to hold the email address.

Is there really a need for a new field to hold the email address instead of using the username?  It probably makes sense to just have the username as the email address.

If a new field is thought to be necessary, discussion should be added to #382.

**Comment by roverwolf** [comment]
You might want to split this PR so that the organisation fix can be merged in right away while any discussion on the email field takes place.

**Comment by JosephLeon** [comment]
I think we should use emails as usernames instead of having both usernames and emails. Will loop @brandonopened  in on this issue

**Comment by brandonopened** [comment]
WIll making username an email address affect existing accounts?

**Comment by roverwolf** [comment]
We can ensure it doesn't.
1. Make sure the email service does not try to send emails to a username that does not look like an email address
2. Allow (and possibly encourage?) users with non-email usernames to be changed to email addresses.

**Comment by roverwolf** [comment]
Per #371 and Brandon's [message](https://opened.slack.com/archives/C6Y1RSQKC/p1518801240000188) on Slack we will **not** add an extra email field but instead have the username be the email address.

@JorgeLu1s Please update the PR to not add the new column.

**Comment by JorgeLu1s** [comment]
ok @roverwolf I'm going to close this PR and create a new one just for the new organization fix

**Pull request closed without merging**
