### PR TITLE
Completing the CASE importer

### PR DESCRIPTION
**Pull request by JorgeLu1s**
setting the missing properties, I'm not sure if this is completed now, please let me know if I'm missing something

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/49)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Salt/SiteBundle/Service/CaseImport.php, line 41 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki64ZwmnCIF-wZm00UT:-Ki64ZwnH3MthZQuPul0:b5byq69) ([raw file](https://github.com/opensalt/opensalt/blob/8aae686240e3f6ca5fc89114607b4a5183b445f9/src/Salt/SiteBundle/Service/CaseImport.php#L41)):*
> ```PHP
>      * @return ObjectManager
>      */
>     public function getEntityManager(): ObjectManager
> ```

Why did you remove the return type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by JorgeLu1s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Salt/SiteBundle/Service/CaseImport.php, line 41 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki64ZwmnCIF-wZm00UT:-Ki68t-r7ScBr_kfMu5i:b3nxlf8) ([raw file](https://github.com/opensalt/opensalt/blob/8aae686240e3f6ca5fc89114607b4a5183b445f9/src/Salt/SiteBundle/Service/CaseImport.php#L41)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

Why did you remove the return type?
</blockquote></details>

Because I got a syntax error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/Resources/assets/js/lsdoc/index.js, line 291 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki6HDpDusUxxuHZFMpR:-Ki6HDpDusUxxuHZFMpS:b-xbnldc) ([raw file](https://github.com/opensalt/opensalt/blob/c2230a44742e24ba58ec151e16df38e618d272a3/app/Resources/assets/js/lsdoc/index.js#L291)):*
>  file = e.target.result;

It doesn't look like `file` has been defined anywhere, probably should be `var file = ...` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Salt/SiteBundle/Service/CaseImport.php, line 41 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki64ZwmnCIF-wZm00UT:-Ki6HXLj1zL4DAohGjk2:brob6za) ([raw file](https://github.com/opensalt/opensalt/blob/8aae686240e3f6ca5fc89114607b4a5183b445f9/src/Salt/SiteBundle/Service/CaseImport.php#L41)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

Because I got a syntax error
</blockquote></details>

Are you using PHP 7.1 ?  What was the error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by JorgeLu1s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/Resources/assets/js/lsdoc/index.js, line 291 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki6HDpDusUxxuHZFMpR:-Ki6z4AL8emkHUELf-fF:bi0galv) ([raw file](https://github.com/opensalt/opensalt/blob/c2230a44742e24ba58ec151e16df38e618d272a3/app/Resources/assets/js/lsdoc/index.js#L291)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>  file = e.target.result;

It doesn't look like `file` has been defined anywhere, probably should be `var file = ...` here.
</blockquote></details>

yes sure

---

*[src/Salt/SiteBundle/Service/CaseImport.php, line 41 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki64ZwmnCIF-wZm00UT:-Ki6yXtpyySc7cWf_cHl:b8et5ot) ([raw file](https://github.com/opensalt/opensalt/blob/8aae686240e3f6ca5fc89114607b4a5183b445f9/src/Salt/SiteBundle/Service/CaseImport.php#L41)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

Are you using PHP 7.1 ?  What was the error?
</blockquote></details>

parse error, expecting `';'' or '{''` that was the error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Salt/SiteBundle/Service/CaseImport.php, line 41 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/49#-Ki64ZwmnCIF-wZm00UT:-Ki75aDYiI-Vz3QMSwQ2:b9em3pd) ([raw file](https://github.com/opensalt/opensalt/blob/8aae686240e3f6ca5fc89114607b4a5183b445f9/src/Salt/SiteBundle/Service/CaseImport.php#L41)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

parse error, expecting `';'' or '{''` that was the error
</blockquote></details>

Odd.  [Return typehints](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) were added in PHP 7.0, so that should not cause a syntax error when using PHP 7.1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Comment by roverwolf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/49)*

**Pull request merged**
