### PR TITLE
Change label on login page 'email' to 'username'

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/59)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/59)*

**Comment by roverwolf** [comment]
The Behat tests need to be updated to look for the new "Username" text instead of the old "Email Address" text.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/59#-:-KilD721DcEaGkB1JwTS:b-4g1poz)*

**Comment by roverwolf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Salt/UserBundle/Resources/views/Security/login.html.twig, line 20 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/59#-KilDWPlCL9c86PeZOqs:-KilDWPlCL9c86PeZOqt:b-5utwd3) ([raw file](https://github.com/opensalt/opensalt/blob/520e68be44ffd36271c4325830a92cce51252b76/src/Salt/UserBundle/Resources/views/Security/login.html.twig#L20)):*
> ```Twig
>                 <form action="{{ path('login') }}" method="post">
>                     <div class="form-group">
>                         <label for="username">Username:</label>
> ```

The behat tests and context needs to be updated to use the new text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/59)*

**Comment by lmsilvera** [comment]
@roverwolf PR uptdated.

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/59)*

**Pull request merged**
