### PR TITLE
Save assosiation correctly

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/53)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 200 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/53#-KiH_4TxbwKRUDVkQxpr:-KiH_4TxbwKRUDVkQxps:b-wj42ff) ([raw file](https://github.com/opensalt/opensalt/blob/abd078a765847d5706b233aee256611ad3d7c00b/src/GithubFilesBundle/Service/GithubImport.php#L200)):*
> ```PHP
>             } elseif (!filter_var($elementAssociated, FILTER_VALIDATE_URL) === false) {
>                 $association->setDestinationNodeUri($elementAssociated);
>                 $association->setDestinationNodeIdentifier(Uuid::uuid5(Uuid::NAMESPACE_URL, $elementAssociated));
> ```

The if determined that this is not a URL, so we probably want to use a different namespace than NAMESPACE_URL.

You can generate a uuid for the namespace here and add it as an appropriate constant somewhere (LsAssociation maybe?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/53)*

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/53)*

**Comment by lmsilvera** [comment]
*[src/GithubFilesBundle/Service/GithubImport.php, line 200 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/53#-KiH_4TxbwKRUDVkQxpr:-KiHfEOJ75nqSBGPK700:b-k2coml) ([raw file](https://github.com/opensalt/opensalt/blob/abd078a765847d5706b233aee256611ad3d7c00b/src/GithubFilesBundle/Service/GithubImport.php#L200)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

The if determined that this is not a URL, so we probably want to use a different namespace than NAMESPACE_URL.

You can generate a uuid for the namespace here and add it as an appropriate constant somewhere (LsAssociation maybe?).
</blockquote></details>

well, I'm passing the new URI, that not relevante?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/53)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 200 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/53#-KiH_4TxbwKRUDVkQxpr:-KiHiQFxzTl4pyWhJA-l:b-65nuxs) ([raw file](https://github.com/opensalt/opensalt/blob/abd078a765847d5706b233aee256611ad3d7c00b/src/GithubFilesBundle/Service/GithubImport.php#L200)):*
<details><summary><i>Previously, lmsilvera (Luis SSilvera) wrote…</i></summary><blockquote>

well, I'm passing the new URI, that not relevante?
</blockquote></details>

A URI is not a URL, and the URL namespace from RFC 4122 is for URLs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/53)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 200 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/53#-KiH_4TxbwKRUDVkQxpr:-KiV8EdshV4Zx88bUQ9T:bvdyh1v) ([raw file](https://github.com/opensalt/opensalt/blob/abd078a765847d5706b233aee256611ad3d7c00b/src/GithubFilesBundle/Service/GithubImport.php#L200)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

A URI is not a URL, and the URL namespace from RFC 4122 is for URLs. 
</blockquote></details>

Ahh, I missed the ! in `!var === false`.  Makes reading the line a bit awkward, but good enough (would have been clearer if it was just `var === false` and switching the elseif content with the else).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/53)*

**Pull request merged**
