### PR TITLE
Adding navigation between folders in github-import dialogue

### PR DESCRIPTION
**Pull request by JorgeLu1s**
changed "import framework" by "import from ASN" in lsdoc/index button

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/41)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 26 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnHZRpQIio6De5lec:-KgVnHZSudpHD9xzR6va:bsabgog) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L26)):*
>   {% if is_granted('ROLE_USER') or framework.adoptionStatus != 'Draft' %}

This was removed and should not go back in, the check (for "Private Draft") is now done in the controller.    

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 32 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnDn_0DeWVO6utjhp:-KgVnDn_0DeWVO6utjhq:b-8vp3dl) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L32)):*
>  {% endif %}
>                     {# PW note: if there are any folders that don't have any documents, they'll be hidden via CSS (see 

This was removed, and should not go back in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/41)*

**Comment by JorgeLu1s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 26 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnHZRpQIio6De5lec:-KgVpejRecCqegsw8edB:b-yxjp82) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L26)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>   {% if is_granted('ROLE_USER') or framework.adoptionStatus != 'Draft' %}

This was removed and should not go back in, the check (for "Private Draft") is now done in the controller.    

</blockquote></details>

ok, so should I remove it and push again?

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 32 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnDn_0DeWVO6utjhp:-KgVphslROr7RWhSxdc9:b-yxjp82) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L32)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>  {% endif %}
>                     {# PW note: if there are any folders that don't have any documents, they'll be hidden via CSS (see 

This was removed, and should not go back in.
</blockquote></details>

ok, so should I remove it and push again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/41)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 26 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnHZRpQIio6De5lec:-KgVn8TBspCnF3rEDy7j:b-5wconm) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L26)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

ok, so should I remove it and push again?
</blockquote></details>

Yes, please.

---

*[src/CftfBundle/Resources/views/LsDoc/index.html.twig, line 32 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/41#-KgVnDn_0DeWVO6utjhp:-KgVqGrRyISIaQUjvk2r:b-5wconm) ([raw file](https://github.com/opensalt/opensalt/blob/e0f4ce6fdc18e5954dfc9820ee5d11c921f68dff/src/CftfBundle/Resources/views/LsDoc/index.html.twig#L32)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

ok, so should I remove it and push again?
</blockquote></details>

Yes, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/41)*

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/41)*

**Pull request merged**
