### PR TITLE
update framework with CSV (Update and derivative)

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/75)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 5 of 11 files at r1, 1 of 5 files at r3, 5 of 6 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/CftfBundle/Controller/LsDocController.php, line 184 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7NHE3qeNmr43jZEf:-KmY7NHFIy87UfAodjic:bt8p01t) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L184)):*
> ```PHP
>      * @Route("/doc/{id}/update", name="lsdoc_update")
>      * @Method("POST")
>      * @Security("is_granted('create', 'lsdoc')")
> ```

If this is changing the document, this should probably be checking `is_granted('edit', lsDoc)` instead.

It is correct if this is creating a new document.

---

*[src/CftfBundle/Controller/LsDocController.php, line 209 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7fQSGD3WQRGuazu0:-KmY7fQSGD3WQRGuazu1:bt8p01t) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L209)):*
> ```PHP
>      * @Route("/doc/{id}/update/derivative", name="lsdoc_update_derivative")
>      * @Method("POST")
>      * @Security("is_granted('create', 'lsdoc')")
> ```

If this is changing the document, this should probably be checking `is_granted('edit', lsDoc)` instead.

It is correct if this is creating a new document.

---

*[src/CftfBundle/Entity/LsAssociation.php, line 294 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7o6ms4elg9e8Ntld:-KmY7o6ms4elg9e8Ntle:b-n42jcu) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsAssociation.php#L294)):*
> ```PHP
>             'replacedBy' =>                   static::REPLACED_BY,
>             'hasSkillLevel' =>                static::SKILL_LEVEL,
>             'cfAssociationGroupIdentifier' => static::RELATED_TO,
> ```

Is `cfAssociationGroupIdentifier` expected here?  That is not a type of association, but an attribute of one.

---

*[src/CftfBundle/Entity/LsAssociation.php, line 513 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY8lzukpPGJBwF0AxH:-KmY8lzukpPGJBwF0AxI:b-efjfhm) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsAssociation.php#L513)):*
>         if ($this->getDestinationNodeIdentifier()) {
>             return $this->getDestinationNodeIdentifier();
>         }

Should this be added?  I believe `getDestination()` should only be getting an actual destination (URI) and not just an identifier.  The URI is a required field.

---

*[src/CftfBundle/Entity/LsItem.php, line 484 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY9GQTKcatoqXLvy9b:-KmY9GQTKcatoqXLvy9c:b-43yuye) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsItem.php#L484)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>             if ($derivated) {
>                 $newExacAssoc = $newLsDoc->createAssociation();
>                 $newExacAssoc->setOrigin($newChild);
>                 $newExacAssoc->setType(LsAssociation::EXACT_MATCH_OF);
>                 $newExacAssoc->setDestination($child);
>                 $newChild->addAssociation($newExacAssoc);
>             }
</details>

Is this to replace `copyToLsDoc()` ?  What is the intended difference?

Should this association get the passed association group set on it?

---

*[src/CftfBundle/Repository/LsDocRepository.php, line 308 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmYAYUO8o8ZY5WfQ1p1:-KmYAYUO8o8ZY5WfQ1p2:buad0f6) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Repository/LsDocRepository.php#L308)):*
> ```PHP
>      * @param LsDoc $oldDoc
>      * @param LsDoc $newDoc
>      * @param \Closure|null $progressCallback
> ```

This parameter seems to be missing on the function.  Should it be in the docblock?

---

*[src/CftfBundle/Repository/LsDocRepository.php, line 324 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmYAKDwmJG-z4r49DVs:-KmYAKDwmJG-z4r49DVt:b-vbrci6) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Repository/LsDocRepository.php#L324)):*
> ```PHP
>         $newLsDoc->setUser($oldLsDoc->getUser());
>         $newLsDoc->setOwnedBy($oldLsDoc->getOwnedBy());
>         $newLsDoc->setAssociationGroupings($oldLsDoc->getAssociationGroupings());
> ```

Association groupings belong to an LsDoc, so they would have to be duplicated as well.

---

*[src/CftfBundle/Resources/views/DocTree/view.html.twig, line 225 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmYApAAR4QFZa-Nwiku:-KmYApAAR4QFZa-Nwikv:bhivwld) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Resources/views/DocTree/view.html.twig#L225)):*
> ```Twig
> </div>
> 
> {% if createRights %}
> ```

Should everyone who can create a document see this, or only those who can edit this particular document?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Controller/LsDocController.php, line 184 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7NHE3qeNmr43jZEf:-KmYQLx-3Mm4y4llzMMv:b-ks8sqa) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L184)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

If this is changing the document, this should probably be checking `is_granted('edit', lsDoc)` instead.

It is correct if this is creating a new document.
</blockquote></details>

ok, that make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Controller/LsDocController.php, line 209 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7fQSGD3WQRGuazu0:-KmYQSmTYY0b0fk7b63H:b-9jwb1a) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L209)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

If this is changing the document, this should probably be checking `is_granted('edit', lsDoc)` instead.

It is correct if this is creating a new document.
</blockquote></details>

here, I need create a new framework "derivatived".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Entity/LsAssociation.php, line 513 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY8lzukpPGJBwF0AxH:-KmYV3anxEP96btWrmRP:b-o4qk6b) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsAssociation.php#L513)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>         if ($this->getDestinationNodeIdentifier()) {
>             return $this->getDestinationNodeIdentifier();
>         }

Should this be added?  I believe `getDestination()` should only be getting an actual destination (URI) and not just an identifier.  The URI is a required field.
</blockquote></details>

yes, I did that testing something. xD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Entity/LsItem.php, line 484 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY9GQTKcatoqXLvy9b:-KmYWpmYJQySJsjrWXPz:b-rmfsmo) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsItem.php#L484)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>             if ($derivated) {
>                 $newExacAssoc = $newLsDoc->createAssociation();
>                 $newExacAssoc->setOrigin($newChild);
>                 $newExacAssoc->setType(LsAssociation::EXACT_MATCH_OF);
>                 $newExacAssoc->setDestination($child);
>                 $newChild->addAssociation($newExacAssoc);
>             }

Is this to replace `copyToLsDoc()` ?  What is the intended difference?

Should this association get the passed association group set on it?

</blockquote></details>

yes, :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by roverwolf** [comment]
*[src/CftfBundle/Controller/LsDocController.php, line 209 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7fQSGD3WQRGuazu0:-KmYcBCFCt7oVpG56_qx:bdh5e83) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L209)):*
<details><summary><i>Previously, lmsilvera (Luis SSilvera) wrote…</i></summary><blockquote>

here, I need create a new framework "derivatived".
</blockquote></details>

We might want to change the URL if it is not updating the framework, something like `/doc/{id}/derive` ?

But the docblock comment seems to indicate that it is updating the framework given a file, not creating a new framework.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
@roverwolf PR already updated.

**Comment by roverwolf** [comment]
Reviewed 4 of 10 files at r5, 2 of 4 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/CftfBundle/Controller/LsDocController.php, line 184 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7NHE3qeNmr43jZEf:-Kmb2e9K0Vm4Kf5LnlMK:b-vivxnc) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L184)):*
<details><summary><i>Previously, lmsilvera (Luis SSilvera) wrote…</i></summary><blockquote>

ok, that make sense.
</blockquote></details>

When using `is_granted('edit', ...)` you need to pass in the doc to check (`lsDoc`), not the string 'lsdoc'.

---

*[src/CftfBundle/Controller/LsDocController.php, line 209 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7fQSGD3WQRGuazu0:-Kmb2rSEH91-7HYgYrDu:baelxqy) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Controller/LsDocController.php#L209)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

We might want to change the URL if it is not updating the framework, something like `/doc/{id}/derive` ?

But the docblock comment seems to indicate that it is updating the framework given a file, not creating a new framework.
</blockquote></details>

This is still under `.../update/`.  Does this update the doc or just create a new derived one?  If only the latter then we should probably remove '/update' from the URL.

---

*[src/CftfBundle/Entity/LsAssociation.php, line 294 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7o6ms4elg9e8Ntld:-Kmb3Bmh7FPWRbMfCtrS:b4awx46) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsAssociation.php#L294)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

Is `cfAssociationGroupIdentifier` expected here?  That is not a type of association, but an attribute of one.
</blockquote></details>

I am still unclear.  When would 'cfAssociationGroupIdentifier' ever be used as a value for the association type?

There is a specific field for the association group on `LsAssociation`, there would never be an association object created from an item to an association group.

---

*[src/CftfBundle/Entity/LsDefAssociationGrouping.php, line 57 at r7](https://reviewable.io:443/reviews/opensalt/opensalt/75#-Kmb49XVurx0fVKZlkbO:-Kmb49XVurx0fVKZlkbP:b9k7due) ([raw file](https://github.com/opensalt/opensalt/blob/212e17c41e5d7c349fe805fd8d332be04efee123/src/CftfBundle/Entity/LsDefAssociationGrouping.php#L57)):*
> ```PHP
>     public function duplicateToLsDoc(LsDoc $newLsDoc): LsDefAssociationGrouping
>     {
>         $newAssociationGrouping = clone $this;
> ```

You will need to ensure that the identifier (and URI) are changed for the new LsDefAssociationGrouping since there cannot be multiple objects with the same identifier.

---

*[src/CftfBundle/Entity/LsItem.php, line 484 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY9GQTKcatoqXLvy9b:-Kmb4T7oQUgwG4PuCm2w:b-xjehbr) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsItem.php#L484)):*
<details><summary><i>Previously, lmsilvera (Luis SSilvera) wrote…</i></summary><blockquote>

yes, :+1: 
</blockquote></details>

You didn't answer the question about if this is to replace `copyToLsDoc()`, and what the intended difference is between what this should do with the added `$derived` argument and what `copyToLsDoc()` does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Entity/LsAssociation.php, line 294 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY7o6ms4elg9e8Ntld:-Kmb91RIcW8svZESeDoL:bjzumhn) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsAssociation.php#L294)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

I am still unclear.  When would 'cfAssociationGroupIdentifier' ever be used as a value for the association type?

There is a specific field for the association group on `LsAssociation`, there would never be an association object created from an item to an association group.
</blockquote></details>

yes, this is a type on the CSV.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
*[src/CftfBundle/Entity/LsItem.php, line 484 at r4](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmY9GQTKcatoqXLvy9b:-Kmb9dVH-qGoJFtqmZ0p:b-aimy5n) ([raw file](https://github.com/opensalt/opensalt/blob/f819cee381b44238b1e788ab0ccaa2273db0d7f5/src/CftfBundle/Entity/LsItem.php#L484)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

You didn't answer the question about if this is to replace `copyToLsDoc()`, and what the intended difference is between what this should do with the added `$derived` argument and what `copyToLsDoc()` does.
</blockquote></details>

hm, sorry I hadn't seen that function. No differences, maybe this would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by roverwolf** [comment]
Reviewed 1 of 10 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
@roverwolf PR ready

**Comment by roverwolf** [comment]
Reviewed 5 of 5 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/CftfBundle/Controller/LsDocController.php, line 209 at r9](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmbPuxhnrAL7K1kOwGS:-KmbPuxhnrAL7K1kOwGT:bwlp1d9) ([raw file](https://github.com/opensalt/opensalt/blob/395f45899edf49ba2caecdbe3937648c137b6224/src/CftfBundle/Controller/LsDocController.php#L209)):*
>  * @Security("is_granted('create', lsDoc)")

For the 'create' check you need to pass the string 'lsdoc' since there is no existing lsDoc to check if you have access to it, as opposed to the 'edit' check where one needs to check that the user has access to that lsDoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
@roverwolf PR updated.

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/CftfBundle/Controller/LsDocController.php, line 209 at r9](https://reviewable.io:443/reviews/opensalt/opensalt/75#-KmbPuxhnrAL7K1kOwGS:-Kmc7nH_Y5KALkzsq-8Y:by4dm84) ([raw file](https://github.com/opensalt/opensalt/blob/395f45899edf49ba2caecdbe3937648c137b6224/src/CftfBundle/Controller/LsDocController.php#L209)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

>  * @Security("is_granted('create', lsDoc)")

For the 'create' check you need to pass the string 'lsdoc' since there is no existing lsDoc to check if you have access to it, as opposed to the 'edit' check where one needs to check that the user has access to that lsDoc.
</blockquote></details>

The value needed to be lower case, not camel case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/75)*

**Comment by lmsilvera** [comment]
@roverwolf  PR ready

**Pull request merged**
