### PR TITLE
Added email and user_type columns to users table

### PR DESCRIPTION
**Pull request by JorgeLu1s**
related to KMS-2458

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/308)

### CODE REVIEW

**Comment by brandonopened** [comment]
I understand the desire to not accept this until there is a use case for it; the idea was to continue to do these types of PR's in stages. IE the DB work, then the UI work it relies on? I'm fine either way just adding color as to why it was done this way.

**Comment by roverwolf** [comment]
Without being linked to an issue (even as a part of the issue) and not even a description of how the fields are to be used it is impossible to review PRs like this.

What are the fields for?  Is the *email* field intended to replace the *username* field in some way?  Or is it a record of if the user has allowed emails to be sent to them?  How does the *user_type* field differ from the existing *roles*?  etc.  They are both marked as required fields but no data exists for them, so they cannot be applied as-is anyway.

**Comment by brandonopened** [comment]
#371 Add validation to account_self_creation page to make username an email address

**Comment by roverwolf** [comment]
@brandonopened Note that #371 might actually remove the need for this PR.
- [ ] #371 has the username being an email address, this PR adds it as a separate field.
- [ ] This PR also adds a "user type" column that has no definition for what it is for (255 character string).

**Comment by brandonopened** [comment]
Jorge what is usertype?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brandonopened** [comment]
Very true. I think we should add email address a field for potential other uses(eventually auto-password reset, commenting); we can't force username to be an email address yet because like you said not all instances will require it.

**Comment by roverwolf** [comment]
Closing as a new PR has been created that would obsolete this one.

**Pull request closed without merging**
