### PR TITLE
New simple importer

### PR DESCRIPTION
**Pull request by JorgeLu1s**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/39)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 130 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/39#-KfvQav_Xlpubt0OqgM_:-KfvQav_Xlpubt0OqgMa:bvqm59x) ([raw file](https://github.com/opensalt/opensalt/blob/6d24f61595ea87a1fcce97dc91c592f88a8ae61d/src/GithubFilesBundle/Service/GithubImport.php#L130)):*
> ```PHP
> 
>         $lsItem->setLsDoc($lsDoc);
>         $lsItem->setIdentifier($data[$lsItemKeys['identifier']]);
> ```

Note that the *Identifier* has to be a **globally-unique** value.  It is usually intended to be a UUID.

Saves will fail if a second import tries to use the same values (such as if they use a simple sequence in the document).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/39)*

**Comment by JorgeLu1s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 130 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/39#-KfvQav_Xlpubt0OqgM_:-KfvWo-uN5UIzOZAbBEV:b-r2pikc) ([raw file](https://github.com/opensalt/opensalt/blob/6d24f61595ea87a1fcce97dc91c592f88a8ae61d/src/GithubFilesBundle/Service/GithubImport.php#L130)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

Note that the *Identifier* has to be a **globally-unique** value.  It is usually intended to be a UUID.

Saves will fail if a second import tries to use the same values (such as if they use a simple sequence in the document).
</blockquote></details>

I set the identifier because the new template has an "identifier" column. 
so should I not assign an identifier and let the app set one by itself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/39)*

**Comment by roverwolf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 130 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/39#-KfvQav_Xlpubt0OqgM_:-KfvbB4yhzc-bB7rNQ8C:b-ccovat) ([raw file](https://github.com/opensalt/opensalt/blob/6d24f61595ea87a1fcce97dc91c592f88a8ae61d/src/GithubFilesBundle/Service/GithubImport.php#L130)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

I set the identifier because the new template has an "identifier" column. 
so should I not assign an identifier and let the app set one by itself?
</blockquote></details>

You should not assign it unless you know that it will be globally unique.

I believe the identifier column is supposed to be a "local identifier" that allows for referencing parents from inside the csv file, as well as possibly referencing previously imported items so that they can be updated.

For the latter there will need to be something saved with that value (possibly a new field) so that it could be found again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/39)*

**Comment by JorgeLu1s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 130 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/39#-KfvQav_Xlpubt0OqgM_:-KfvcEn3NnVDOcSDi2eM:brf17ez) ([raw file](https://github.com/opensalt/opensalt/blob/6d24f61595ea87a1fcce97dc91c592f88a8ae61d/src/GithubFilesBundle/Service/GithubImport.php#L130)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

You should not assign it unless you know that it will be globally unique.

I believe the identifier column is supposed to be a "local identifier" that allows for referencing parents from inside the csv file, as well as possibly referencing previously imported items so that they can be updated.

For the latter there will need to be something saved with that value (possibly a new field) so that it could be found again.
</blockquote></details>

ok, I didn't know hot the identifier should work, so I'll add a new field like 'localIdentifier'.

About the update the item if already exists, should I add it in this branch or should I create a new branch and make a new PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/39)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 130 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/39#-KfvQav_Xlpubt0OqgM_:-KfvdUVb5V2crhhzRu2f:b2edgmz) ([raw file](https://github.com/opensalt/opensalt/blob/6d24f61595ea87a1fcce97dc91c592f88a8ae61d/src/GithubFilesBundle/Service/GithubImport.php#L130)):*
<details><summary><i>Previously, JorgeLu1s (Jorge Luis) wrote…</i></summary><blockquote>

ok, I didn't know hot the identifier should work, so I'll add a new field like 'localIdentifier'.

About the update the item if already exists, should I add it in this branch or should I create a new branch and make a new PR?
</blockquote></details>

I'll merge this PR so that it can be tested (it will work fine if the identifier is a unique UUID for example), then we can do the changes in a new PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/39)*

**Pull request merged**
