### PR TITLE
Update Excel Spreadsheet Exports.

### PR DESCRIPTION
**Pull request by holisticnetworking**
This pull request reorganizes the columns of the Excel spreadsheet export of frameworks and adds a column for Origin and Destination URI.

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/856)

### CODE REVIEW

**Comment by holisticnetworking** [comment]
I have no idea what's wrong with the StyleCI stuff. Where is the sentence that tells me in so many words, what's wrong? I see nothing. I click on details, and I get a list of changed files.

**Comment by holisticnetworking** [comment]
@roverwolf Can you explain what this log file is telling me? I'm not sure how I could have altered how many arguments were added to the docker call where the execution stops?
https://travis-ci.org/opensalt/opensalt/builds/572901312?utm_source=github_status&utm_medium=notification

**Comment by holisticnetworking** [comment]
@roverwolf This page tells me literally nothing about what is wrong. Just gives me a diff which, while certainly different, doesn't really look wrong?
https://github.styleci.io/analyses/8K1xPD?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by holisticnetworking** [comment]
@roverwolf It appears that the Travis commit number may not be getting added to this section of the build file:

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

Line 24 of build.sh relies on this variable to create the full `docker build` statement?

**Comment by roverwolf** [comment]
> It appears that the Travis commit number may not be getting added to this section of the build file:
...

@holisticnetworking 
The issue is that the `VERSION` file is not a single line (a merge conflict was committed) which is used on line 21 of `build.sh`.

**Comment by holisticnetworking** [comment]
@roverwolf I'm not sure what's happening, but the code in my current branch no longer includes the siteURL function. Yet the tests keep failing on that line of code. Is there some way to ensure that the most up-to-date code is getting checked? Last commit 57fd466ef3b20e76e20bf63f56b11c520f0791e8.

**Comment by roverwolf** [comment]
@holisticnetworking It is using the most up-to-date version of the branch that you have pushed to GitHub.  I just checked out the branch `tjb-export-update-only` out and it has the function `siteURL()` in `AbstractLsBase.php`.

**Comment by roverwolf** [comment]
@holisticnetworking This PR ended up getting a lot of extra commits to unneccessary filles and would not rebase nicely against develop (it looks like it may have been forked from release/2.2 instead of develop).

I have created a new branch and PR #873 that contains the relevant commits from this branch for the single file that I believe you actually want changed.  Please review that PR to verify that it satisfies what you were trying to do here.

**Comment by roverwolf** [comment]
Closed in favour of #873

**Pull request closed without merging**
