### PR TITLE
List org admin

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/61)

### CODE REVIEW

**Comment by roverwolf** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Salt/UserBundle/Repository/UserRepository.php, line 55 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/61#-KjAJVRZ_iYlAo-hsVoG:-KjAJVRZ_iYlAo-hsVoH:byiwpwb) ([raw file](https://github.com/opensalt/opensalt/blob/b7e09a15e24c8f3547fe9e50404367f4a56b1d16/src/Salt/UserBundle/Repository/UserRepository.php#L55)):*
> ```PHP
>      * @return array
>      */
>     public function findAdminUsersPerOrganization(){
> ```

To find the admin users "Per Organization", shouldn't the organization be passed in and used in the query?

Or should this just be called `findAdminUsers` ?

---

*[src/Salt/UserBundle/Resources/views/Security/login.html.twig, line 59 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/61#-KjAK0KGtLmkCReSYZQg:-KjAK0KGtLmkCReSYZQh:bc29nj5) ([raw file](https://github.com/opensalt/opensalt/blob/b7e09a15e24c8f3547fe9e50404367f4a56b1d16/src/Salt/UserBundle/Resources/views/Security/login.html.twig#L59)):*
> ```Twig
>                     </thead>
>                     <tbody>
>                         {% for user in org_admins %}
> ```

You might want to group the list by organization to make it easier for the user to look through vs a completely unsorted list of people.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/61)*

**Comment by roverwolf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Salt/UserBundle/Resources/views/Security/login.html.twig, line 59 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/61#-KjAK0KGtLmkCReSYZQg:-KjAWpVQVLeq8exzbIYV:bb556cu) ([raw file](https://github.com/opensalt/opensalt/blob/b7e09a15e24c8f3547fe9e50404367f4a56b1d16/src/Salt/UserBundle/Resources/views/Security/login.html.twig#L59)):*
<details><summary><i>Previously, roverwolf (David Ward) wrote…</i></summary><blockquote>

You might want to group the list by organization to make it easier for the user to look through vs a completely unsorted list of people.
</blockquote></details>

We might also want this on a separate page as it could get long, and hopefully not needed very often.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/61)*

**Comment by lmsilvera** [comment]
@roverwolf PR already updated for review.

**Comment by roverwolf** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/61)*

**Pull request merged**
