### PR TITLE
Show importer errors

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/67)

### CODE REVIEW

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[app/DoctrineMigrations/Version20170511220330.php, line 20 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBfn_eNvJjJ2-fAxDl:-KkBfn_eNvJjJ2-fAxDm:b-puk8oz) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/app/DoctrineMigrations/Version20170511220330.php#L20)):*
> "ALTER TABLE importation_logs ADD message_type VARCHAR(30) NULL"
This should probably be merged with the other migration so that the entire definition is in one file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/Salt/SiteBundle/Controller/DefaultController.php, line 69 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBo6yV0CRHjCEKsMgJ:-KkBo6yWl9V2uh3O5-z9:b-2g2hlc) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/src/Salt/SiteBundle/Controller/DefaultController.php#L69)):*
>         $lsDocId = $request->request->get('lsDocId');
>         $lsDoc = $em->getRepository('CftfBundle:LsDoc')->find(44);
Looks like debugging code left over.  Assuming `44` should be `$lsDocId`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/Salt/SiteBundle/Controller/DefaultController.php, line 73 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBoKqANeXc12KLFKyb:-KkBoKqANeXc12KLFKyc:b1kf3g9) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/src/Salt/SiteBundle/Controller/DefaultController.php#L73)):*
>             $em->flush();
`flush()` should be outside the loop as it is an expensive operation and in this case there is no need for it to be done one by one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/Salt/SiteBundle/Controller/DefaultController.php, line 72 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBoc2BkEzk5XtL5Tu3:-KkBoc2BkEzk5XtL5Tu4:b-79epsk) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/src/Salt/SiteBundle/Controller/DefaultController.php#L72)):*
>             $em->persist($log);
It looks like `$log` is already persisted (coming from the database), so no need to persist it again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by roverwolf** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 101 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBowTsudOfbpYtUNJE:-KkBowTsudOfbpYtUNJF:bjc03dv) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/src/GithubFilesBundle/Service/GithubImport.php#L101)):*
>                 $em->flush();
`flush()` should not be in the loop.  There is already a `flush()` at the end of the method, so probably not needed here at all.

---

*[src/GithubFilesBundle/Service/GithubImport.php, line 110 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkBozz1bI0muDPdZS_m:-KkBozz1bI0muDPdZS_n:blvngk9) ([raw file](https://github.com/opensalt/opensalt/blob/b0e28feebc822adc069436cdf9216de6c364f247/src/GithubFilesBundle/Service/GithubImport.php#L110)):*
> $em->flush();
`flush()` should not be inside the loop.  There is already a `flush()` at the end of the method, so not needed here at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by lmsilvera** [comment]
@roverwolf PR already updated.

**Comment by roverwolf** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/DoctrineMigrations/Version20170510163859.php, line 26 at r2](https://reviewable.io:443/reviews/opensalt/opensalt/67#-KkHUgrwPoft6qgMevg8:-KkHUgrwPoft6qgMevg9:bo5bujm) ([raw file](https://github.com/opensalt/opensalt/blob/a19617409a979b36b1a321cfe4da30788ec28052/app/DoctrineMigrations/Version20170510163859.php#L26)):*
> PRIMARY KEY(id, ls_doc_id))

Is ls_doc_id needed in the primary key?  id is an auto increment field and should be unique.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Comment by lmsilvera** [comment]
@roverwolf PR already updated.

**Comment by roverwolf** [comment]
Reviewed 2 of 11 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/67)*

**Pull request merged**
