### PR TITLE
Add github auth config documentation and updating readme

### PR DESCRIPTION
**Pull request by lmsilvera**
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/26)

### CODE REVIEW

**Comment by roverwolf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[app/config/parameters.yml.dist, line 25 at r1](https://reviewable.io:443/reviews/opensalt/opensalt/26#-KbQTIomCwmNw4iPWYZp:-KbQTIomCwmNw4iPWYZq:byv1fjv) ([raw file](https://github.com/opensalt/opensalt/blob/bbfb43d729e308fa029545ba2d79158705468d1c/app/config/parameters.yml.dist#L25)):*
> ```
> 
>     local_uri_host: http://localhost:3000/
>     github_redirect_uri: ~
> ```

Is there a reason we need to pass this in instead of having the code generate the absolute path to the route that this is pointing to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/26)*

**Comment by lmsilvera** [comment]
@roverwolf because the component that I use for authenticate users with github send the github_redirect_uri with null value and then github redirect with an error like "uri mistmach" cause by the redirect_uri should be the equals.

**Comment by roverwolf** [comment]
I understand that we need to send the value, but I think it should be able
to be generated based on the route to the salt endpoint that GitHub would
use.

I am assuming that the 'github_login' route would be the correct one, so to
generate the URL to pass would use something like

```
$this->generateUrl('github_login', [], UrlGeneratorInterface::ABSOLUTE_URL)
```

**Comment by lmsilvera** [comment]
Hm, make sense.

**Comment by lmsilvera** [comment]
@roverwolf PR updated & ready.

**Comment by roverwolf** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/opensalt/opensalt/26#-KbkkFAn0Spx_BgwbVDH:-KbkkFAn0Spx_BgwbVDI:bsd1xp0) (no related file):*
@lmsilvera I've added information to the readme file to show explain the two methods of setting the github access keys.

If you agree with the way it is worded then I'll merge the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opensalt/opensalt/26)*

**Pull request merged**
