### PR TITLE
Export Framework as a stylized PDF 

### PR DESCRIPTION
**Pull request by adlearningmate**
Export Framework as a PDF format 
1. Logged in opensalt with user role (Super User, Admin, Editor, Super Editor )
2. Go to the Framework detail page
3. You can see Export button after clicking on it, we will get button for Styled PDF.
which will download the framework details- CFDocuments, CFItems and Association in PDF format

---
This change is [Reviewable](https://reviewable.io/reviews/opensalt/opensalt/423)

### CODE REVIEW

**Comment by roverwolf** [comment]
Which GitHub Issue is this for?

**Comment by roverwolf** [comment]
Why are we restricting this from being used by anonymous users?

**Comment by brandonopened** [comment]
It shouldn't be limited to anonymous but available to anonymous... it references #247

**Comment by roverwolf** [comment]
Okay, I also found #137 which sounds like it may apply.

@adlearningmate Based on the comment by @brandonopened it looks like step 1 is incorrect and any user (including anonymous users) should be able to use this feature.

**Comment by brandonopened** [comment]
@adlearningmate yes, let's go ahead and make it available to all users.

**Pull request closed without merging**
